---
title: "Association Study Summary Report"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggmap)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(rmarkdown)
library(httr)
library(plumber)
library(jsonlite)
library(RCurl)
library(rjson)
```

## Association Study Summary Report

This is the Association Study Summary Report. For more details on the workflow see <https://github.com/shukwong/gwas-pipelines/blob/master/README.md>.

Describe the input data
```{r}
ls()
```


##  Plots

Manhattan  plots
```{r echo=FALSE}

# Base URL path

# Building RESTful APIs via Plumber:

#* @apiTitle Simple API

#* Echo provided text
#* @param text The text to be echoed in the response
#* @get /echo
function(text = "") {
  list(
    message_echo = paste("The text is:", text)
  )
}

base_url = "https://storage.cloud.google.com/fc-bb2e1cbd-3b7c-460b-bb9e-b0031b84d809/b35607aa-e7f4-4b68-aaca-38f1a1d0f1ed/run_association_test/c63b31f1-bd91-4cf0-a16f-6022a4626d55/call-make_bolt_plots/shard-0/cacheCopy/bolt_complete_set_bq_bmi_curr_co_results_merged_P_manhattan.png?authuser=2"

full_url = paste0(base_url, "gs://fc-bb2e1cbd-3b7c-460b-bb9e-b0031b84d809/b35607aa-e7f4-4b68-aaca-38f1a1d0f1ed/run_association_test/c63b31f1-bd91-4cf0-a16f-6022a4626d55/call-make_bolt_plots/shard-0/cacheCopy/bolt_complete_set_bq_bmi_curr_co_results_merged_P_manhattan.png")

# encode the URL with characters for each space.
full_url <- URLencode(full_url)

# Convert JSON to an image?
bolt_complete_set_bq_bmi_curr_co_results_merged_P_manhattan_png <- getURL(full_url)
bolt_complete_set_bq_bmi_curr_co_results_merged_P_manhattan_png
## [1] "list"


plot(pressure)
```

QQ  plots
```{r echo=FALSE}
plot(pressure)
```

## links to GWAS summary data


## Appendix: maybe running time etc
